/**
 * Writes an idempotent SQL file that imports catalogue CSVs, for databases the import CLI cannot
 * reach over HTTPS (the hosted project from a locked-down container: apply it with the Supabase
 * connector or the SQL editor). Same parsing and grouping as the importer; insert-only:
 *   - products keyed by source_ref "<category id>::<name key>" (on conflict do nothing),
 *   - sizes attached by looking the product up by source_ref, so a re-run adds nothing.
 * Categories must already exist (matched by slug). Costs are never set.
 *
 *   npx tsx scripts/import-to-sql.mts --supplier "Shrivi Limited" --out file.sql a.csv:source_a b.csv:source_b
 */
import { readFileSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { readImportCsv } from "../src/lib/import/csv";
import { groupItems, slugify } from "../src/lib/import/parse-name";
import { uniqueSlug } from "../src/lib/import/plan";

const { values, positionals } = parseArgs({
  allowPositionals: true,
  options: { supplier: { type: "string" }, out: { type: "string" }, chunk: { type: "string", default: "250" } },
});
if (!values.supplier || !values.out || positionals.length === 0) throw new Error("usage: --supplier NAME --out FILE a.csv:source …");

const q = (s: string | null | undefined) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);
const slugs = new Set<string>();
const products: string[] = [];
const variants: string[] = [];
const seen = new Set<string>();

for (const spec of positionals) {
  const [file, source] = spec.split(":");
  const { rows, errors } = readImportCsv(readFileSync(file, "utf8"));
  if (errors.length) throw new Error(`${file}: ${errors.map((e) => `line ${e.line} ${e.message}`).join("; ")}`);
  for (const p of groupItems(rows).products) {
    const cat = slugify(p.category);
    const key = `${cat}::${p.nameKey}`;
    if (!seen.has(key)) {
      seen.add(key);
      products.push(`(${q(cat)},${q(p.name.slice(0, 200))},${q(uniqueSlug(p.name, slugs))},${q(p.description)},${q(p.image)},${q(source)},${q(p.nameKey)})`);
    }
    for (const v of p.variants) {
      const sort = Math.min(2_000_000_000, Math.max(0, Math.round(v.sortKey)));
      const vat = v.vatBp ?? "null::int"; // null -> the category default VAT
      variants.push(`(${q(cat)},${q(p.nameKey)},${q(v.sizeLabel.slice(0, 60))},${sort},${vat},${q(v.sku)},${q(v.source.slice(0, 500))})`);
    }
  }
}

const chunk = Number(values.chunk);
const parts: string[] = [
  `-- Generated by scripts/import-to-sql.mts. Idempotent and insert-only; no costs.`,
  `insert into public.suppliers (name) select ${q(values.supplier)} where not exists (select 1 from public.suppliers where lower(name) = lower(${q(values.supplier)}));`,
];
for (let i = 0; i < products.length; i += chunk) {
  parts.push(`insert into public.products (category_id, name, slug, description, image_path, source, source_ref)
select c.id, v.name, v.slug, v.description, v.image_path, v.source, c.id || '::' || v.name_key
from (values ${products.slice(i, i + chunk).join(",\n")}) v(category, name, slug, description, image_path, source, name_key)
join public.categories c on c.slug = v.category
on conflict do nothing;`);
}
for (let i = 0; i < variants.length; i += chunk) {
  parts.push(`insert into public.product_variants (product_id, size_label, size_sort, supplier_id, vat_rate_bp, sku, source_ref)
select p.id, v.size_label, v.size_sort, s.id, coalesce(v.vat_rate_bp, c.default_vat_rate_bp), v.sku, v.source_ref
from (values ${variants.slice(i, i + chunk).join(",\n")}) v(category, name_key, size_label, size_sort, vat_rate_bp, sku, source_ref)
join public.categories c on c.slug = v.category
join public.products p on p.source_ref = c.id || '::' || v.name_key
cross join (select id from public.suppliers where lower(name) = lower(${q(values.supplier)}) order by created_at limit 1) s
on conflict do nothing;`);
}
writeFileSync(values.out, parts.join("\n\n") + "\n");
console.log(`${products.length} products, ${variants.length} sizes -> ${values.out} (${parts.length} statements)`);
